---
- name: Check if Docker is installed
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_max_cache_age_installs }}" # Stricter cache time for installs than updates
    pkg:
      - docker
      - docker-compose
    state: latest
  notify: Enable Docker

# Remember that item is a reserved word for loops
- name: Deploy containers with Compose
  docker_compose:
    project_src: "{{ item }}"
  loop: "{{ compose_files }}"