---
- name: Check if Docker is installed
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_max_cache_age_installs }}" # Stricter cache time for installs than updates
    pkg:
      # - docker
      # - docker-compose
    state: latest
  notify: Enable Docker

- name: Create Docker Network
  community.docker.docker_network:
    name: homelab
    driver: bridge
    ipam_options:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1

# Remember that item is a reserved keyword for loops/with_items
- name: Deploy containers with Compose
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
    pull: yes
    state: present
  with_items: "{{ compose_files }}"
