---
- name: Install important software packages
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_max_cache_age_installs }}" # Stricter cache time for installs than updates
    pkg:
      "{{ packages }}"
    state: latest
    install_recommends: true
  register: install_results
  notify: 
    - Enable Docker
  # TODO: - Configure Samba

# - debug: msg="{{ install_results }}"