---
- name: Run OS maintenance
  hosts: all
  become: yes

  roles: 
    - maintenance

  # TODO: Cannot be run on localhost, find a solution or alternative
  post_tasks:
    - name: Reboot OS
      reboot:
        pre_reboot_delay: 10 # Wait 10 seconds, just in case