---

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PASSWORD= # optional
      - HASHED_PASSWORD= # optional
      - SUDO_PASSWORD= # optional
      - SUDO_PASSWORD_HASH= # optional
      - PROXY_DOMAIN=code-server.my.domain # optional
      - DEFAULT_WORKSPACE=/home # optional
    volumes:
      - ./code-server/config:/config
      - /home/:/home
      - /media:/media
    # ports:
      # - 8443:8443
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.0.1.12

  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./pyload-ng/config:/config
      - /media/hdd/BolloNAS/Descargas/pyload-ng:/downloads
    ports:
      # - 8000:8000 # WebUI port
      - 9666:9666 #optional
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.0.1.13

networks:
  homelab:
    external: true

