---
- include_vars: ../deploy/defaults/main.yml

- name: Stop and remove Compose containers
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
    state: absent
    timeout: 120
  with_items: "{{ compose_files }}"

- name: Update and restart Docker containers
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
    pull: always
    state: present
  with_items: "{{ compose_files }}"
  register: docker_result

# Print update result
# - debug: msg="{{ docker_result }}"
