---
# TODO Check samba alternative: ksmbd (kernel implementation of Samba)
packages:
  - exa
  - git
  - sudo
  - rsync
  - docker
  - docker-compose 
  - wget
  - curl
  - nano
  - htop
  - iperf
  - iperf3
  - pip
  - gnupg
  - rsync
  - bleachbit
  - speedtest-cli
  - samba
  - samba-common-bin
  # - neofetch

apt_max_cache_age_installs: 3600 # One hour

# compose-files:
# Put path here to compose file(s)