---
packages:
  - git
  - sudo
  - rsync
 # - docker.io # Uncomment if preferring Debian/Ubuntu official package
  - uptimed
  - wget
  - curl
  - nano
  - htop
  - iperf
  - iperf3
  - python3-full
  - python-is-python3
  - pip
  - python3-docker
  - gnupg
  - rsync
  - bleachbit
  - speedtest-cli
  # - samba
  # - samba-common-bin
  - ksmbd-tools
  - neofetch

apt_max_cache_age_installs: 3600 # One hour

# TODO: Check samba alternative: ksmbd (kernel implementation of Samba)
# Samba related configuration
samba_conf: /etc/samba/smb.conf
samba_user: root
samba_name: BolloNAS
samba_shared: /media/hdd/BolloNAS

# NOTE: This paths are relative to playbook_dir, so initial path is pelochus-homelab/ansible
compose_files:
  - ../docker/media
  - ../docker/monitoring
  - ../docker/networking
  - ../docker/others
