---
packages:
  - git
  - sudo
  - rsync
 # - docker.io # Better use the official docker install guide
  - uptimed
  - wget
  - curl
  - nano
  - htop
  - iperf3
  - python3-full
  - python-is-python3
  - pip
  - python3-docker
  - gnupg
  - rsync
  - bleachbit
  - speedtest-cli
  # - samba
  # - samba-common-bin
  - ksmbd-tools
  - neofetch

apt_max_cache_age_installs: 3600 # One hour

# Valid for both ksmbd and smbd
# samba_conf: /etc/samba/smb.conf
samba_conf: /etc/ksmbd/ksmbd.conf
samba_user: "{{ user }}"
samba_name: BolloNAS
samba_shared: /media/hdd/BolloNAS
samba_template: ksmbd.conf.j2

# NOTE: This paths are relative to playbook_dir, so initial path is pelochus-homelab/ansible
compose_files:
  - ../docker/media
  - ../docker/monitoring
  - ../docker/networking
  - ../docker/others
