---
packages:
  - exa
  - git
  - sudo
  - rsync
  - docker
  - docker-compose 
  - wget
  - curl
  - nano
  - htop
  - iperf
  - iperf3
  - python
  - python3
  - pip
  - gnupg
  - rsync
  - bleachbit
  - speedtest-cli
  - samba
  - samba-common-bin
  # - neofetch

apt_max_cache_age_installs: 3600 # One hour

# TODO: Check samba alternative: ksmbd (kernel implementation of Samba)
# Samba related configuration
samba_conf: /etc/samba/smb.conf
samba_user: root
samba_name: BolloNAS
samba_shared: /media/hdd/BolloNAS

# TODO: Check if this path is possible (or use ./docker)
compose_files:
  - ../../docker/media
  - ../../docker/monitoring
  - ../../docker/networking
  - ../../docker/others