---
- name: Enable Docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Configure Samba
  template:
    src: "{{ samba_template }}"
    dest: "{{ samba_conf }}"
    owner: {{ user }}
    group: {{ user }}
  notify: Enable Samba

- name: Enable Samba
  service:
    name: smbd
    stated: restarted
    enabled: yes
