---
- name: Enable Docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Configure Samba
  template:
    src: smb.conf.j2 
    dest: "{{ samba_conf }}"
    owner: root
    group: root
  notify: Enable Samba

- name: Enable Samba
  service:
    name: smbd
    stated: restarted
    enabled: yes