---
# Include here: NGINX Proxy Manager, PiHole?, PiVPN?...

# TODO: Uncomment for final version when trying out NGINX Proxy Manager
# services:
#  nginx-proxy:
#    container_name: nginx-proxy
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - ./nginx/data:/data
#      - ./nginx/letsencrypt:/etc/letsencrypt
